### ISSUE TITLE
**suggestion (performance):** Leverage setup-node's built-in npm caching

### ISSUE THREAD

**Issue by Dev-Re2906** [Dev-Re2906/stackblitz-webcontainer-api-starter-2wmijcya#11]
**suggestion (performance):** Leverage setup-node's built-in npm caching

Add `cache: 'npm'` to the `with` block to enable npm dependency caching and improve install speed.

Suggested implementation:

```
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

```

```
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

```

_Originally posted by @sourcery-ai[bot] in https://github.com/Dev-Re2906/stackblitz-webcontainer-api-starter-2wmijcya/pull/10#discussion_r2151379356_
